# Generated by Django 3.2.5 on 2021-11-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaidProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="英語表記"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="名前")),
                ("content", models.TextField(blank=True, verbose_name="自己紹介")),
                (
                    "thumbnail_image",
                    models.ImageField(
                        null=True, upload_to="maidlist_thubnail", verbose_name="サムネイル画像"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        null=True, upload_to="maidlist_main", verbose_name="メイン画像"
                    ),
                ),
                ("visible", models.BooleanField(default=True, verbose_name="表示")),
                (
                    "order",
                    models.IntegerField(db_index=True, default=0, verbose_name="表示順"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
