# Generated by Django 3.2.5 on 2021-11-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maidlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maidprofile",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="maidprofile",
            name="main_image",
            field=models.ImageField(
                null=True, upload_to="maidlist_main/", verbose_name="メイン画像"
            ),
        ),
        migrations.AlterField(
            model_name="maidprofile",
            name="thumbnail_image",
            field=models.ImageField(
                null=True, upload_to="maidlist_thubnail/", verbose_name="サムネイル画像"
            ),
        ),
    ]
