# Generated by Django 3.2.9 on 2021-11-25 13:06

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maidlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maidprofile",
            name="og_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="maidlist_ogp/", verbose_name="OGP画像"
            ),
        ),
        migrations.AlterField(
            model_name="maidprofile",
            name="content",
            field=mdeditor.fields.MDTextField(blank=True, verbose_name="自己紹介"),
        ),
    ]
