# Generated by Django 3.2.9 on 2021-11-26 19:51

import apps.stafflist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maidlist", "0003_maidprofile_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maidprofile",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.stafflist.models.main_image_upload_to,
                verbose_name="メイン画像",
            ),
        ),
        migrations.AlterField(
            model_name="maidprofile",
            name="og_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.stafflist.models.og_image_upload_to,
                verbose_name="OGP画像",
            ),
        ),
        migrations.AlterField(
            model_name="maidprofile",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.stafflist.models.thumbnail_image_upload_to,
                verbose_name="サムネイル画像",
            ),
        ),
    ]
