# Generated by Django 3.2.9 on 2022-02-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='キー')),
                ('event_name', models.CharField(max_length=100, verbose_name='イベント名')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chousei.event')),
            ],
            options={
                'unique_together': {('event', 'start_datetime')},
            },
        ),
        migrations.CreateModel(
            name='EventPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名前')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chousei.event')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, '×'), (1, '△'), (2, '○')], verbose_name='回答')),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chousei.eventdate')),
                ('event_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chousei.eventperson')),
            ],
            options={
                'unique_together': {('event_person', 'event_date')},
            },
        ),
    ]
