# Generated by Django 3.2.9 on 2021-11-26 19:52

import apps.stafflist.models
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="英語表記"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="名前")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "content",
                    mdeditor.fields.MDTextField(blank=True, verbose_name="自己紹介"),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.stafflist.models.thumbnail_image_upload_to,
                        verbose_name="サムネイル画像",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.stafflist.models.main_image_upload_to,
                        verbose_name="メイン画像",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.stafflist.models.og_image_upload_to,
                        verbose_name="OGP画像",
                    ),
                ),
                ("visible", models.BooleanField(default=True, verbose_name="表示")),
                (
                    "order",
                    models.IntegerField(db_index=True, default=0, verbose_name="表示順"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "イベントオーガナイザー自己紹介",
                "verbose_name_plural": "イベントオーガナイザー自己紹介",
                "ordering": ["order"],
            },
        ),
    ]
